### ISSUE TITLE
compiled wheel for windows

### ISSUE THREAD

**Issue by ydkhatri** [K0lb3/astc_decomp#2]
Can you package this as a wheel on PyPI? This is basically for windows users as most end users don't have visual studio installed for compiling.

**Comment by ydkhatri** [comment]
If you'd like, I can compile these, so all you have to do is upload them.

**Comment by ydkhatri** [comment]
OK, here are the compiled windows wheels for py 3.6, 3.7, 3.8 both x86 & x64.
[astc_decomp-wheels-win.zip](https://github.com/K0lb3/astc_decomp/files/4893208/astc_decomp-wheels-win.zip)
Here is for macos python 3.7, 3.8 (3.6 has issues compiling)
[wheels-macos.zip](https://github.com/K0lb3/astc_decomp/files/4903628/wheels-macos.zip)

**Comment by K0lb3** [comment]
Worked out fine on all systems via github actions.
The wheels for all systems are up now.

**Comment by ydkhatri** [comment]
This does not have the wheel for 32 bit python for Windows. In the default installation, python will install 32 bit version on windows (regardless of 32/64 bit os).

**Comment by K0lb3** [comment]
I fixed the workflow,
it now creates x86 wheels as well.

**Comment by ydkhatri** [comment]
Hi again, can you make the python 3.9 wheel available on pypi too?

**Comment by ydkhatri** [comment]
Thanks
